# **Combinatoire : notions préalables**
### Romain GERARD

Importer les packages.

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display, Math, Latex
from sympy import symbols, expand, latex

## Factorielle et coefficient binomial

In [2]:
def facto_rec(x):
    """
    Calcule la factorielle de x de manière récursive.
    """
    if x == 0:
        return 1
    return x * facto_rec(x-1)

def coeff_bino(n, k):
    """
    Calcule le coefficient binomial C(n, k).
    """
    return facto_rec(n) // (facto_rec(k)*facto_rec(n-k))

def coeff_bino_rec(n, k):
    """
    Calcule le coefficient binomial C(n, k) de manière récursive.
    """
    if k > n:
        return 0
    if k == 0 or k == n:
        return 1
    
    return coeff_bino_rec(n-1, k-1) + coeff_bino_rec(n-1, k)

# Exemple: 7!
x = 7
display(Math(rf"{x}! = {facto_rec(x)}"))

# Exemple: C(10, 5)
n, k = 10, 5
display(Math(rf"\binom{{{n}}}{{{k}}} = {coeff_bino_rec(n, k)}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Permutations

In [3]:
def permute_rec(lst):
    """
    Retourne la liste de toutes les permutations de lst, de manière récursive.
    """
    if len(lst) == 0:
        return [[]]

    result = []
    for i in range(len(lst)):
        current = lst[i]
        remaining = lst[:i] + lst[i+1:]
        for e in permute_rec(remaining):
            result.append([current] + e)
    return result

N = 7
A = list(range(1, N+1))
sigma_n = permute_rec(A)

print("A =", A)
print()
print("Ensemble de toutes les n-permutations de A :")
print(sigma_n[0])
print(sigma_n[1])
print(sigma_n[2])
print(sigma_n[3])
print(". . .")
print(sigma_n[-2])
print(sigma_n[-1])

display(Math(rf"|\sigma_n| = {len(sigma_n)}"))
display(Math(rf"|A|! = {facto_rec(len(A))}"))


A = [1, 2, 3, 4, 5, 6, 7]

Ensemble de toutes les n-permutations de A :
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 7, 6]
[1, 2, 3, 4, 6, 5, 7]
[1, 2, 3, 4, 6, 7, 5]
. . .
[7, 6, 5, 4, 3, 1, 2]
[7, 6, 5, 4, 3, 2, 1]


<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Nombre de Stirling de seconde espèce

In [25]:
def calcule_stirling_rec(n, k):
    """
    Calcule le nombre de Stirling de seconde espèce S(n, k)
    selon une définition récursive.
    
    S(n, k) = S(n-1, k-1) + k * S(n-1, k)
    avec les cas de base :
       - S(0, 0) = 1
       - S(n, 0) = 0 pour n > 0
       - S(0, k) = 0 pour k > 0
    """
    if n == 0 and k == 0:
        return 1
    if (n == 0 and k > 0) or (n > 0 and k == 0):
        return 0

    return calcule_stirling_rec(n-1, k-1) + k*calcule_stirling_rec(n-1, k)

display(Math(r"""
\textbf{Nombres de Stirling de seconde espèce} :
\\
\text{Définition récursive : }
S(n, k) = S(n-1, k-1) + k \, S(n-1, k),
\quad S(0, 0) = 1,
\quad S(x, 0) = S(0, y) = 0 \quad \text{pour tout } x>0, y>0.
"""))

# Exemple: S(4,1), S(4,2), S(4,3) et S(4,4)
display(Math(rf"S(4,1) = {calcule_stirling_rec(4,0)}"))
display(Math(rf"S(4,1) = {calcule_stirling_rec(4,1)}"))
display(Math(rf"S(4,2) = {calcule_stirling_rec(4,2)}"))
display(Math(rf"S(4,3) = {calcule_stirling_rec(4,3)}"))
display(Math(rf"S(4,4) = {calcule_stirling_rec(4,4)}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [6]:
# Table des nombres de Stirling de seconde espèce (n/k).
table_stirling = np.zeros((N, N))
table_n, table_k = table_stirling.shape
for i in range(table_n):
    ind_n = i + 1
    for j in range(table_k):
        ind_k = j + 1
        table_stirling[i, j] = calcule_stirling_rec(ind_n, ind_k)
print("Nombres de Stirling de seconde espèce (n/k):\n", table_stirling, sep="")

Nombres de Stirling de seconde espèce (n/k):
[[  1.   0.   0.   0.   0.   0.   0.]
 [  1.   1.   0.   0.   0.   0.   0.]
 [  1.   3.   1.   0.   0.   0.   0.]
 [  1.   7.   6.   1.   0.   0.   0.]
 [  1.  15.  25.  10.   1.   0.   0.]
 [  1.  31.  90.  65.  15.   1.   0.]
 [  1.  63. 301. 350. 140.  21.   1.]]


## Nombre de Bell

In [ ]:
def calcule_bell_iter(n):
    res = 0
    for k in range(1, n+1):
        res += calcule_stirling_rec(n, k)
    return res

def calcule_bell_rec(n):
    if n == 0:
        return 1
    
    res = 0
    for m in range(n):
        res += coeff_bino(n-1, m) * calcule_bell_rec(m)
    return res

display(Math(r"""
\textbf{Nombres de Bell} : B(n) = \sum_{k=1}^{n} S(n,k).
\\
\text{Définition récursive : }
B(n) = \sum_{m=0}^{n-1} \binom{n-1}{m} \, B(m), \quad B(0) = 1.
"""))

# Calcul des 8 premiers nombres de Bells.
N = 7
for num in range(N+1):
    display(Math(rf"B({num}) = {calcule_bell_rec(num)}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>