# **Combinatoire : notions préalables**
### Romain GERARD

Importer les packages.

In [14]:
import numpy as np
import pandas as pd
from IPython.display import display, Math, Latex
from sympy import symbols, expand, latex

## Factorielle et coefficient binomial

In [16]:
def facto_rec(x):
    """
    Calcule la factorielle de x de manière récursive.
    """
    if x == 0:
        return 1
    return x * facto_rec(x-1)

def coeff_bino(n, k):
    """
    Calcule le coefficient binomial C(n, k).
    """
    return facto_rec(n) // (facto_rec(k)*facto_rec(n-k))

def coeff_bino_rec(n, k):
    """
    Calcule le coefficient binomial C(n, k) de manière récursive.
    """
    if k > n:
        return 0
    if k == 0 or k == n:
        return 1
    
    return coeff_bino_rec(n-1, k-1) + coeff_bino_rec(n-1, k)

# Exemple: 7!
x = 7
display(Math(rf"{x}! = {facto_rec(x)}"))

# Exemple: C(10, 5)
n, k = 10, 5
display(Math(rf"\binom{{{n}}}{{{k}}} = {coeff_bino_rec(n, k)}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Permutations

In [29]:
def permute_rec(lst):
    """
    Retourne la liste de toutes les permutations de lst, de manière récursive.
    """
    if len(lst) == 0:
        return [[]]

    result = []
    for i in range(len(lst)):
        current = lst[i]
        remaining = lst[:i] + lst[i+1:]
        for e in permute_rec(remaining):
            result.append([current] + e)
    return result

n = 7
A = list(range(1, n+1))
sigma_n = permute_rec(A)

print("A =", A)
print()
print("Ensemble de toutes les n-permutations de A :")
print(sigma_n[0])
print(sigma_n[1])
print(sigma_n[2])
print(sigma_n[3])
print(". . .")
print(sigma_n[-2])
print(sigma_n[-1])

display(Math(rf"|\sigma_n| = {len(sigma_n)}"))
display(Math(rf"|A|! = {facto_rec(len(A))}"))


A = [1, 2, 3, 4, 5, 6, 7]

Ensemble de toutes les n-permutations de A :
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 7, 6]
[1, 2, 3, 4, 6, 5, 7]
[1, 2, 3, 4, 6, 7, 5]
. . .
[7, 6, 5, 4, 3, 1, 2]
[7, 6, 5, 4, 3, 2, 1]


<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Nombre de Stirling de seconde espèce

In [28]:
def calcule_stirling_rec(n, k):
    """
    Calcule le nombre de Stirling de seconde espèce S(n, k)
    selon une définition récursive.
    
    S(n, k) = S(n-1, k-1) + k * S(n-1, k)
    avec les cas de base :
       - S(0, 0) = 1
       - S(n, 0) = 0 pour n > 0
       - S(0, k) = 0 pour k > 0
    """
    if n == 0 and k == 0:
        return 1
    if (n == 0 and k > 0) or (n > 0 and k == 0):
        return 0

    return calcule_stirling_rec(n-1, k-1) + k*calcule_stirling_rec(n-1, k)

display(Math(r"""
\textbf{Nombres de Stirling de seconde espèce} :
\\
\text{Définition récursive : }
S(n, k) = S(n-1, k-1) + k \, S(n-1, k),
\quad S(0, 0) = 1,
\quad S(x, 0) = S(0, y) = 0 \quad \text{pour tout } x>0, y>0.
"""))

# Exemple
n = 4
for k in range(5):
    display(Math(rf"S({n},{k}) = {calcule_stirling_rec(n,k)}"))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [26]:
# Table des nombres de Stirling de seconde espèce (n/k).
table_stirling = np.zeros((7, 7))
table_n, table_k = table_stirling.shape
for i in range(table_n):
    ind_n = i + 1
    for j in range(table_k):
        ind_k = j + 1
        table_stirling[i, j] = calcule_stirling_rec(ind_n, ind_k)
print("Nombres de Stirling de seconde espèce (n/k):\n", table_stirling, sep="")

Nombres de Stirling de seconde espèce (n/k):
[[  1.   0.   0.   0.   0.   0.   0.]
 [  1.   1.   0.   0.   0.   0.   0.]
 [  1.   3.   1.   0.   0.   0.   0.]
 [  1.   7.   6.   1.   0.   0.   0.]
 [  1.  15.  25.  10.   1.   0.   0.]
 [  1.  31.  90.  65.  15.   1.   0.]
 [  1.  63. 301. 350. 140.  21.   1.]]


## Nombre de Bell

In [23]:
def calcule_bell_iter(n):
    res = 0
    for k in range(1, n+1):
        res += calcule_stirling_rec(n, k)
    return res

def calcule_bell_rec(n):
    if n == 0:
        return 1
    
    res = 0
    for m in range(n):
        res += coeff_bino(n-1, m) * calcule_bell_rec(m)
    return res

display(Math(r"""
\textbf{Nombres de Bell} : B(n) = \sum_{k=1}^{n} S(n,k).
\\
\text{Définition récursive : }
B(n) = \sum_{m=0}^{n-1} \binom{n-1}{m} \, B(m), \quad B(0) = 1.
"""))

# Calcul des 8 premiers nombres de Bells.
for num in range(8):
    display(Math(rf"B({num}) = {calcule_bell_rec(num)}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Partitions

In [ ]:
def partitionne_stirling_rec(lst, k):
    """
    Retourne la liste de toutes les partitions de lst en k sous-listes (blocs) en
    s'inspirant de la définition récursive du nombre de Stirling de seconde espèce:
    
                        S(n, k) = S(n-1, k-1) + k * S(n-1, k)
    """
    n = len(lst)

    # -------------
    # Cas de base :
    # -------------

    # Si k = 0 et n = 0, alors on a une seule partition vide.
    if k == 0 and n == 0:
        return [[]]
    
    # Si k = 0 ou n = 0, mais pas les deux en même temps,
    # alors il n'existe aucune partition.
    if (k == 0 or n == 0) and (k != n):
        return []
    
    # Si k = n, chaque élément de lst doit être dans son propre bloc.
    if k == n:
        return [ [[x] for x in lst] ]
    
    # Si k = 1, il n'y a qu'un seul bloc contenant tous les éléments.
    if k == 1:
        return [[lst]]
    
    # Si k > n, il n'existe pas de partition car on ne peut
    # pas répartir n éléments en plus de n blocs non vides.
    if k > n:
        return []
    
    # ----------------------------------------------------
    # Récurrence :
    # 1) On met lst[0] dans son propre bloc, et on partitionne
    #    lst[1:] en (k-1) blocs.
    # 2) On met lst[0] dans chacun des blocs d'une partition de
    #    lst[1:] en k blocs.
    # ----------------------------------------------------

    # Initialiser la liste de toutes les partitions.
    lst_part = []
    
    # 1) Ajouter lst[0] dans un nouveau bloc (S(n-1, k-1))
    for part in partitionne_stirling_rec(lst[1:], k - 1):
        # On ajoute le bloc [lst[0]] devant
        new_part = [[lst[0]]] + part
        lst_part.append(new_part)
    
    # 2) Ajouter lst[0] dans chacun des blocs.
    for part in partitionne_stirling_rec(lst[1:], k):
        # Pour chaque partition obtenue, on crée k nouvelles partitions
        # où lst[0] est inséré dans un seul bloc par partition.
        for i in range(len(part)):
            new_part = []
            for j, bloc in enumerate(part):
                if j == i:
                    # On insère lst[0] dans le bloc d'indice i ...
                    new_part.append([lst[0]] + bloc)
                else:
                    # ... sinon on recopie le bloc tel quel.
                    new_part.append(bloc[:])
            lst_part.append(new_part)
    
    return lst_part


# Exemple
A = list(range(1, 5))
k = 3
partitions = partitionne_stirling_rec(A, k)
for p in partitions:
    print(p)

display(Math(rf"S({len(A)},{k}) = {len(partitions)}"))


[[1], [2], [3, 4]]
[[1], [2, 3], [4]]
[[1], [3], [2, 4]]
[[1, 2], [3], [4]]
[[2], [1, 3], [4]]
[[2], [3], [1, 4]]


<IPython.core.display.Math object>

In [43]:
def partitionne_bell(lst):
    '''
    Retourne la liste de toutes les partitions des éléments de lst en s'inspirant
    de la définition du nombre de Bell comme une somme de nombres de Stirling de
    seconde espèce.
    '''
    n = len(lst)
    all_part = []
    for k in range(n+1):
        all_part = all_part + partitionne_stirling_rec(lst, k)
    return all_part

# Exemple
A = list(range(1, 5))
all_partitions = partitionne_bell(A)
for part in all_partitions:
    print(part) 

display(Math(rf"B({len(A)}) = {len(all_partitions)}"))
        

[[1, 2, 3, 4]]
[[1], [2, 3, 4]]
[[1, 2], [3, 4]]
[[2], [1, 3, 4]]
[[1, 2, 3], [4]]
[[2, 3], [1, 4]]
[[1, 3], [2, 4]]
[[3], [1, 2, 4]]
[[1], [2], [3, 4]]
[[1], [2, 3], [4]]
[[1], [3], [2, 4]]
[[1, 2], [3], [4]]
[[2], [1, 3], [4]]
[[2], [3], [1, 4]]
[[1], [2], [3], [4]]


<IPython.core.display.Math object>

# Statistiques sur les permutations